name: PR checks
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  install_node_deps:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: yarn
      
  ts_tests:
    name: typscript tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: yarn test
        
  build_and_preview:
    name: build and deploy preview branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cd emsdk && ./emsdk install 3.1.54 && ./emsdk activate 3.1.54 && source ./emsdk_env.sh && cd .. && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARBON_DOMINION_415509 }}'
          projectId: carbon-dominion-415509

