name: PR checks
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_test_deploy_preview:
    name: build test and deploy preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: yarn
      - run: yarn types
      - run: yarn test
      - run: cd emsdk && ./emsdk install 3.1.54 && ./emsdk activate 3.1.54 && source ./emsdk_env.sh && cd .. && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARBON_DOMINION_415509 }}'
          projectId: carbon-dominion-415509
      

