name: pull-request
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_test_deploy_preview:
    name: test and preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install
        run: yarn
      - name: check types
        run: yarn types
      - name: tests
        run: yarn test
      - name: build
        run: yarn build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARBON_DOMINION_415509 }}'
          projectId: carbon-dominion-415509
      

